### ISSUE TITLE
Wrong Typo? : about

### ISSUE THREAD

**Issue by YuzuRyo61** [eizi2002/eizi2002.github.io#34]
issus になってるけどもしかして issues のこと？
![image](https://user-images.githubusercontent.com/18282413/58481398-4047c180-8197-11e9-9d23-97e301346309.png)

**Comment by Leies-202** [comment]
英語力の無さは相変わらずだったとです…。
https://github.com/eizi2002/eizi2002.github.io/commit/64fd7bb633de1375f9949b0e54b5eeb09b4b6154
